/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { MockRoyaltySendContract } from "./MockRoyaltySendContract";
export type { SplitRoyalty } from "./SplitRoyalty";

export { IERC20__factory } from "./factories/IERC20__factory";
export { MockRoyaltySendContract__factory } from "./factories/MockRoyaltySendContract__factory";
export { SplitRoyalty__factory } from "./factories/SplitRoyalty__factory";
